// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Kurland",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Kurland",
            targets: ["AppModule"],
            bundleIdentifier: "Giovana.Kurland",
            teamIdentifier: "G657ETJXLM",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Enable the camera to complete the next quest."),
                .microphone(purposeString: "Enable the microphone to complete the next quest."),
                .speechRecognition(purposeString: "Enable speech recognition to complete the next quest.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
